# Base Image: Ubuntu 22.04 LTS (Jammy Jellyfish) Vagrant 박스를 사용.
# Vagrant 박스는 HashiCorp Cloud의 Vagrant Discovery에서 검색 가능
# https://portal.cloud.hashicorp.com/vagrant/discover?query=ubuntu%2Fjammy64

Vagrant.configure("2") do |config|
  # VM에 사용할 기본 이미지를 Ubuntu 22.04로 설정.
  config.vm.box = "ubuntu/jammy64"
  
  # 특정 버전의 Ubuntu 22.04 박스를 사용 (버전 20240823.0.1).
  config.vm.box_version = "20240823.0.1"
  
  # VM의 호스트 이름을 'kind'로 설정.
  config.vm.hostname = "kind"
  
  # 현재 디렉토리(`./`)와 VM의 `/vagrant` 디렉토리 간의 디렉토리 동기화를 비활성화.
  # (디렉토리 동기화는 기본적으로 활성화되어 있지만 비활성화 중)
  config.vm.synced_folder "./", "/vagrant", disabled: true
  
  # VM 시작 시 초기 설정을 위해 `init_cfg.sh` 스크립트를 실행.
  config.vm.provision "shell", path: "init_cfg.sh"
  
  # VirtualBox 제공자(Provider) 설정.
  config.vm.provider "virtualbox" do |vb1|
      # 가상 머신에 대한 nested virtualization 설정을 활성화.
      vb1.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      
      # 가상 머신에 할당할 메모리 크기를 16GB로 설정.
      vb1.memory = 16384
      
      # 가상 머신에 할당할 CPU 코어 개수를 8개로 설정.
      vb1.cpus = 8
      
      # 가상 머신 이름을 'kind'로 설정.
      vb1.name = "kind"
      
      # Linked Clone 기능 활성화로 VM 생성 속도를 개선.
      vb1.linked_clone = true
  end
  
  # 내부 네트워크를 설정하여 VM에 고정 IP(192.168.50.10)를 할당.
  config.vm.network "private_network", ip: "192.168.50.10"
  
  # 포트 포워딩 설정: 호스트의 60000 포트를 게스트의 SSH 포트(22)로 포워딩하여 SSH 접속 가능.
  config.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
end
